# Generated by Django 3.1.2 on 2020-11-08 17:09

import discordlogin.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0002_auto_20201108_1313'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', discordlogin.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
